name: pr-review-requester

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
    auto-add-reviewer:
        name: Auto add reviewer to PR
        if: github.event.pull_request
        uses: celestiaorg/.github/.github/workflows/reusable_housekeeping.yml@v0.2.2
        secrets: inherit
        permissions:
          issues: write
          pull-requests: write
        with:
          run-auto-request-review: true